### ISSUE TITLE
Readable version

### ISSUE THREAD

**Issue by Monirzadeh** [DesarrolloAntonio/Shiori-Android-Client#1]
it can be good if app will show readable version of bookmarks too.

**Comment by DesarrolloAntonio** [comment]
> it can be good if app will show readable version of bookmarks too.

Is there any way to access the link of the readable version of a post that is not public?

**Comment by DesarrolloAntonio** [comment]
> it can be good if app will show readable version of bookmarks too.


Is there a way to get the readable from an API with token authorization? I can't display the content in the app if it's not public.

**Comment by aikiharp** [comment]
I would like to see this feature also.
