### ISSUE TITLE
First time run not follow theme settings in android 

### ISSUE THREAD

**Issue by Monirzadeh** [DesarrolloAntonio/Shiori-Android-Client#10]
app theme not follow system them automatically. if you active dark mode in android than open app for first time PageKeeper open in light mode.
It can be good if we have 3 option (default Follow System Settings)

   - Follow system settings
   -  Light Mode
   -  Dark Mode

**Comment by DesarrolloAntonio** [comment]
Added system theme in version 1.04. Now, you can switch between dark, light, and system themes.

**Comment by DesarrolloAntonio** [comment]
I'll take a look at creating a nightly version with continuous integration.
