### ISSUE TITLE
[Feature Request] Compact View

### ISSUE THREAD

**Issue by lokesh-krishna** [DesarrolloAntonio/Shiori-Android-Client#15]
Thank you so much for creating such a gorgeous app! 
Could you consider a compact view, that drops the images? Would be nice to be able to view more links at once.

**Comment by DesarrolloAntonio** [comment]
Yes, I had thought about placing a small photo on the left and the title on the right, and maybe a menu button on the right for all the options.

**Comment by unoukujou** [comment]
I would like to request this as well.

A simple "list view" is much better for me.

When you scroll through hundreds of bookmarks it makes a difference.

**Comment by DesarrolloAntonio** [comment]
> Thank you so much for creating such a gorgeous app! Could you consider a compact view, that drops the images? Would be nice to be able to view more links at once.

I've created a compat view
<img src="https://github.com/DesarrolloAntonio/Shiori-Android-Client/assets/7002198/913f60de-739c-42e3-90b3-a05c6825a333" width="300">

Any suggestion is welcome.
