### ISSUE TITLE
New with a dumb question

### ISSUE THREAD

**Issue by taraletti** [DesarrolloAntonio/Shiori-Android-Client#19]
Hi! I'm new in the app and this is probably the dumbest question I would do: where do I have to create an account to use the app?

**Comment by unoukujou** [comment]
> Hi! I'm new in the app and this is probably the dumbest question I would do: where do I have to create an account to use the app?

You need to get shiori:

https://github.com/go-shiori/shiori

**Comment by taraletti** [comment]
Done and running but I don't find a command to create an account to use the android app

**Comment by unoukujou** [comment]
> Done and running but I don't find a command to create an account to use the android app

https://github.com/go-shiori/shiori/blob/master/docs/Usage.md#using-web-interface

The default password:

username: shiori
password: gopher

Then when you log in you can change it.

**Comment by taraletti** [comment]
Sorry, but the server url?

**Comment by unoukujou** [comment]
When you run this command:

`shiori server`

It will set up the server. The URL is the local IP of the host you are running it on, default port is 8080.

You can check it is working by opening your browser on the same computer you run shiori from and open this url: http://localhost:8080

**Comment by taraletti** [comment]
Only get failed to connect to localhost. In the computer shiori is running

**Comment by unoukujou** [comment]
When you run this command:

`shiori server`

What does it say?

**Comment by taraletti** [comment]
Failed to connect (ip:port)

**Comment by unoukujou** [comment]
Maybe try a different port.

`shiori server -port 8888`

If it works, then you can open http://localhost:8888

**Comment by taraletti** [comment]
> Maybe try a different port.
> 
> `shiori server -port 8888`
> 
> If it works, then you can open http://localhost:8888

it works on my computer with 8000, I'm in and even changed user and password. When I go to pagekeeper now, in

ServeURL: if I put what in command line appears as "remote" plus the 8000 port, says that failed to connect. If I put my IP plus 8000 port, again, I get failed to connect. If I put the complete line of "remote" that appears in shiori serve, I get failed to connect too...

**Comment by unoukujou** [comment]
It should be the local ip address of your computer that is running shiori. If you have a router, that would be the local ip the router assigned to your computer.

In pagekeeper, you would connect by http://ip:8000

ip is the local ip of the computer running shiori. Akso your android device should be connected to the same router via wifi

**Comment by taraletti** [comment]
> It should be the local ip address of your computer that is running shiori. If you have a router, that would be the local ip the router assigned to your computer.
> 
> In pagekeeper, you would connect by http://ip:8000
> 
> ip is the local ip of the computer running shiori. Akso your android device should be connected to the same router via wifi

I just can't find it...using my ip, the ip for the router, the remote ip...nothing works

**Comment by unoukujou** [comment]
Is your computer that is running shiori on Windows?

https://www.digitalcitizen.life/find-ip-address-windows/

**Comment by taraletti** [comment]
> Is your computer that is running shiori on Windows?
> 
> https://www.digitalcitizen.life/find-ip-address-windows/

 Find it. Noticed that shiori is on port 8080, put the IP and 8080 and give me "Handshake failed". Put with 8000 and get failed to connect to (ip port) from (another ip and another port) after 30000 ms

**Comment by unoukujou** [comment]
Handshake failed sounds like you are doing https. Make sure it is http? Without the s?

**Comment by taraletti** [comment]
> Handshake failed sounds like you are doing https. Make sure it is http? Without the s?

Done! Thanks a lot, now two questions

1 - the app will work even if shiori is closed in the pc? 
2 - it's possible to add links on android? or not yet, I'm not finding that option

**Comment by unoukujou** [comment]
You're welcome!

1) shiori needs to be running 24/7. If you close it, you cannot access it. All your shiori data is stored on that PC and served from there.

2) I have not been able to get pagekeeper working for myself but if you open your regular browser on android and go to the shiori URL http://IP:port, you can add bookmarks there without pagekeeper. Pagekeeper is just another way to access shiori. If pagekeeper is working for you, you can probably open a webpage and the bookmark it by sharing that page directly to pagekeeper. I can't try it myself because pagekeeper doesn't work for me.
