### ISSUE TITLE
Thumbnail not show in app

### ISSUE THREAD

**Issue by Monirzadeh** [DesarrolloAntonio/Shiori-Android-Client#2]
app not show thumbnail of bookmarks.
in screenshot it is work but in my test not working. is it a bug or this feature not merge yet?

**Comment by DesarrolloAntonio** [comment]
I can see all the thumbnails, can you send me a link to try

**Comment by DesarrolloAntonio** [comment]
The first three bookmarks that I have did not have a thumbnail, I have deleted them, I have created them again and they are now available, perhaps it is a compatibility problem between versions

**Comment by DesarrolloAntonio** [comment]
> i test that with pagekeeper v 1.02 and stable release of shiori 1.5.5. if i add link with Share menu thumbnail is show up but if you add that from shiori than refresh app thumbnail missing for example test this link https://www.1pezeshk.com/archives/2024/01/lactic-acid-isnt-making-your-muscles-sore.html
> 
> thumbnail work in shiori. in both way(share menu or directly add from server) .
> 
> if you refresh app ,is it check thumbnail for refresh too?

I've tested the link and the thumbnails look fine to me.
![Screenshot_20240115_084345](https://github.com/DesarrolloAntonio/Shiori-Android-Client/assets/7002198/9ce95617-0440-4b2c-92c7-e518767743d4)

**Comment by DesarrolloAntonio** [comment]
> Do you add that from server or app?

From server

**Comment by DesarrolloAntonio** [comment]
> Do you add that from server or app?

and from the app too

**Comment by DesarrolloAntonio** [comment]
> it happen to me time to time.

Have you tried deleting the bookmark and adding it again?

**Comment by DesarrolloAntonio** [comment]
I think I have found the problem. If the URL is saved in this format (http://192.168.1.12:8080/), when the image URL part is added (http://192.168.1.12:8080//bookmark/1/thumb), the slash / gets duplicated. I have implemented a control to remove the slash if it exists.

**Comment by DesarrolloAntonio** [comment]
> Hi. I test latest release on Google Play (v1.05) unfortunately bug still exist.

Can you create a user or environment where I could test from my device?

**Comment by DesarrolloAntonio** [comment]
I've created this for google review, you can test in:
http://144.24.183.231:8085/
user: testing
pass: shiori

**Comment by DesarrolloAntonio** [comment]
I've installed Shiori in Docker using a template, but the template uses a very old version from this image: [https://hub.docker.com/r/radhifadlillah/shiori/tags]. I'll try to update the container.

**Comment by DesarrolloAntonio** [comment]
I've created a new container using the latest image, but the thumbnail is not showing in the app, now I can fix the bug. Here are the server details with the same credentials.
http://144.24.183.231:8086/

**Comment by DesarrolloAntonio** [comment]
In my case the problem was that de bookmark was not public, and there was no access to the image. I have edited the bookmark to make it public, and now it appears.

**Comment by DesarrolloAntonio** [comment]
![Captura de pantalla_área-de-selección_20240123122546](https://github.com/DesarrolloAntonio/Shiori-Android-Client/assets/7002198/fdba097e-34cd-4bf4-b93d-06585a4db892)

**Comment by DesarrolloAntonio** [comment]
I'm using the direct url
http://144.24.183.231:8086/bookmark/1/thumb

**Comment by DesarrolloAntonio** [comment]
I can't send cookies from Android in a straightforward way. The only thing I can think of is to send the sessionID as a parameter in the URL

**Comment by DesarrolloAntonio** [comment]
I've solved the problem including the X-Session-Id in the headers.

**Comment by graphixillusion** [comment]
I'm still having the problem. I can't see anymore the images in the saved bookmarks. I'm using the last version of the app in android 9

**Comment by graphixillusion** [comment]
@DesarrolloAntonio Any news about this?

**Comment by graphixillusion** [comment]
All images are not present.
