### ISSUE TITLE
[feat] longer/permanent login session

### ISSUE THREAD

**Issue by dhruvinsh** [DesarrolloAntonio/Shiori-Android-Client#22]
Thank you dor the great app. I have one suggestion for the login session. If possible, can login session be a longer/permanent?

It is keep experience and if try to share link with past logged in session, pressing save bookmark does nothing. To fix that you have to open the app manually l, click on session expired message and then login again. Only after that if any link shared would work. 

![Screenshot_20240228-060716](https://github.com/DesarrolloAntonio/Shiori-Android-Client/assets/33428164/b972fe4e-70a7-4f52-b12d-04de8a8078e1)

**Comment by DesarrolloAntonio** [comment]
In version 1.11, the session expiration time is 30 days.

**Comment by dhruvinsh** [comment]
I tried it, but the session is expiring the same as before. Haven't seen the change yet. 

I installed it straight from the GitHub release, do I need to clear the cache or anything?

**Comment by DesarrolloAntonio** [comment]
> I tried it, but the session is expiring the same as before. Haven't seen the change yet.
> 
> I installed it straight from the GitHub release, do I need to clear the cache or anything?

Before, the expiration time was set to one day. Log out and try again, if it happens again tomorrow let me know.

**Comment by dhruvinsh** [comment]
Still the same behavior, the session expires within a couple of hours or so.

**Comment by DesarrolloAntonio** [comment]
> Still the same behavior, the session expires within a couple of hours or so.
> 
> This is what the go-shiori logs say,
> 
> ```
> level=warning
> 
> msg=GET /api/bookmarks
> 
> proto=HTTP/1.1
> 
> remote=172.18.0.14:35432
> 
> reqlen=0
> 
> size=25
> 
> status=500
> 
> time=2024-03-02T16:26:58Z
> ```

If the server restart, the session expired

**Comment by dhruvinsh** [comment]
I double checked, and the server wasn't restarted. 

I had a reverse proxy in between and thought it might be stripping the header so I switched to the IP address but still the same result.

Is there anyway I can collect some logs on this app?

**Comment by DesarrolloAntonio** [comment]
> I double checked, and the server wasn't restarted.
> 
> I had a reverse proxy in between and thought it might be stripping the header so I switched to the IP address but still the same result.
> 
> Is there anyway I can collect some logs on this app?

What version of shiori server are you using?

**Comment by dhruvinsh** [comment]
I am using `ghcr.io/go-shiori/shiori:latest`

I will try to see if I can get the version number.

**Comment by dhruvinsh** [comment]
Found the solution: `SHIORI_HTTP_SECRET_KEY` 

I was missing this environment key in my docker deployment causing revalidation every few hours.
