### ISSUE TITLE
Bookmark Update Cache broken

### ISSUE THREAD

**Issue by graphixillusion** [DesarrolloAntonio/Shiori-Android-Client#23]
As the title says, when you try to update cache for selected bookmark, it shows an error (Unknown error) and then the app logs out. This happening with the last 1.11 version. Server 1.6.0rc7

**Comment by DesarrolloAntonio** [comment]
> As the title says, when you try to update cache for selected bookmark, it shows an error (Unknown error) and then the app logs out. This happening with the last 1.11 version. Server 1.6.0rc7

I have released a new version of the app with the bug fixed, let me know if it doesn't work.

**Comment by graphixillusion** [comment]
I haven't anymore the error but the preview thumbnail doesn't appear anymore as before

**Comment by DesarrolloAntonio** [comment]
> I haven't anymore the error but the preview thumbnail doesn't appear anymore as before

I think this is a problem of the cache of the photos, I'll repair for the next release

**Comment by graphixillusion** [comment]
For now i have just two bookmarks saved and it happens for all of them

**Comment by DesarrolloAntonio** [comment]
> For now i have just two bookmarks saved and it happens for all of them

Can you try with versión 1.13?

**Comment by graphixillusion** [comment]
> > For now i have just two bookmarks saved and it happens for all of them
> 
> Can you try with versión 1.13?

seems fixed thank you
