### ISSUE TITLE
[Feature Request] Startup explanation with links to Shiori docs

### ISSUE THREAD

**Issue by Skivling** [DesarrolloAntonio/Shiori-Android-Client#25]
When someone downloads PageKeeper, it just comes up with a connect and log-in window. 
There should be explanation for how it works, explaining you need to host your own server and also linking to the Shiori documentation so people can know how to set it up. 
There should also be a button in settings to allow already logged-in people to view the explanation again.

**Comment by irresistibl** [comment]
Agreed. Needs a link to the docs

**Comment by DesarrolloAntonio** [comment]
> When someone downloads PageKeeper, it just comes up with a connect and log-in window. There should be explanation for how it works, explaining you need to host your own server and also linking to the Shiori documentation so people can know how to set it up. There should also be a button in settings to allow already logged-in people to view the explanation again.

I have placed a button on the login screen and another one in the settings with access to the instructions for installing the server. v1.15

**Comment by Skivling** [comment]
Ok, thanks!
