### ISSUE TITLE
The interface is very large

### ISSUE THREAD

**Issue by Katarn** [DesarrolloAntonio/Shiori-Android-Client#26]
There is little space left for a list of articles.

![image](https://github.com/DesarrolloAntonio/Shiori-Android-Client/assets/6339978/76118598-c60b-4a92-8620-bf073415463a)

**Comment by DesarrolloAntonio** [comment]
I am planning to create a compact view.

**Comment by DesarrolloAntonio** [comment]
I've created a compat view
<img src="https://github.com/DesarrolloAntonio/Shiori-Android-Client/assets/7002198/913f60de-739c-42e3-90b3-a05c6825a333" width="300">

Any suggestion is welcome.

**Comment by Katarn** [comment]
Thank you! But the bottom line with the sections still looks quite large. I suggest doing it like in Squawker.

![image](https://github.com/DesarrolloAntonio/Shiori-Android-Client/assets/6339978/33a6a841-80de-4075-a309-e250ab8b4e5c)

You can also see in your screenshot that the second title line is exactly in the middle of the card’s height. It's like there's a little space missing from the buttons at the bottom of the card. Maybe reduce the line-height of the title a little?

**Comment by DesarrolloAntonio** [comment]
The app uses Google's Material 3, which sets specific dimensions for the bottom bar according to its guidelines. What I can do is move the icon to the side of the text to create more space.
https://m3.material.io/components/tabs/specs

![image](https://github.com/DesarrolloAntonio/Shiori-Android-Client/assets/7002198/c3d59323-38e7-4d64-bf14-a1aadd6a0106)

**Comment by DesarrolloAntonio** [comment]
> > What I can do is move the icon to the side of the text to create more space.
> 
> Great idea.
> 
> And the question is - can the framework switch to other versions of Material for example, for older versions of Android, for which Material 3 is not a native design?

The documentation does not specify what the minimum version is, but in the example project for Jetpack Compose with Material 3, it is using API 21, which is Android 5. There is a feature like 'Dynamic color' that is only available from Android 12 onwards.

https://github.com/android/compose-samples/tree/main/Reply

**Comment by Katarn** [comment]
The new look of compact view is great. Thank you!
