### ISSUE TITLE
The state of the tag list is not remembered

### ISSUE THREAD

**Issue by Katarn** [DesarrolloAntonio/Shiori-Android-Client#29]
I hide them, switch to Settings, then return to the list of bookmarks, and they show up again.

**Comment by DesarrolloAntonio** [comment]
Solved with the new design

**Comment by Katarn** [comment]
Unfortunately, the state is not saved when the application is restarted.

**Comment by DesarrolloAntonio** [comment]
> Unfortunately, the state is not saved when the application is restarted.

Fixed in version 1.18

**Comment by Katarn** [comment]
I can't confirm. I collapse the list of tags, click on Back (the application closes), launch the application again - the list of tags is open.

**Comment by DesarrolloAntonio** [comment]
> I can't confirm. I collapse the list of tags, click on Back (the application closes), launch the application again - the list of tags is open.

I thought you were referring to the state of the selected categories, okay, I will also save the state of whether it is visible.

**Comment by DesarrolloAntonio** [comment]
> I can't confirm. I collapse the list of tags, click on Back (the application closes), launch the application again - the list of tags is open.

Fixed

**Comment by Katarn** [comment]
Yes, it's fixed now. Thank you!
