### ISSUE TITLE
The application takes up an unexpectedly large amount of space after installation

### ISSUE THREAD

**Issue by Katarn** [DesarrolloAntonio/Shiori-Android-Client#33]
In my case, if I clear the cache and data, it shows that the application itself takes up 144 megabytes.

I'm installing the application via the IzzyOnDroid repository. Installation takes 2-3 minutes, which is also strange.

**Comment by DesarrolloAntonio** [comment]
Installed from IzzyOnDroid in a Pixel 3a

<img src="https://github.com/DesarrolloAntonio/Shiori-Android-Client/assets/7002198/e14f9aaa-0e92-4990-a37e-5c344816d5b3" width="300">

**Comment by Katarn** [comment]
I have 144 megabytes, perhaps due to the fact that Android is an old version. Perhaps there are no code optimizations for installation yet.

Does it take longer for you to install than other applications?

**Comment by DesarrolloAntonio** [comment]
> Does it take longer for you to install than other applications?

I just did the installation from IzzyOnDroid and it took 14 seconds.

**Comment by Katarn** [comment]
I was interested in comparison with other applications of a similar amount of functionality. On my phone, applications install in 20-30 seconds, and this takes 2-3 minutes.

**Comment by Katarn** [comment]
It's clear. Thank you. Apparently my smartphone is quite old.
