### ISSUE TITLE
[FEATURE] Show URL after it has been shared to PageKeeper

### ISSUE THREAD

**Issue by Skivling** [DesarrolloAntonio/Shiori-Android-Client#34]
**Is your feature request related to a problem? Please describe.**
I get annoyed when I am bulk sharing a lot of bookmarks to Shiori/PageKeeper, and adding tags, and then I forget what it is for and have to re-do a specific one.

**Describe the solution you'd like**
When a URL is shared to the app, at the top of that UI it should display the URL. As a bonus, it could be a text field and allow the user to tweak the URL before adding it, e.g. removing UTM trackers.

**Describe alternatives you've considered**
I have to exit the dialog, find the one I was up to and then re-share it once I know what tags I want to put on it.

**Additional context**
I see that recent versions have updated the 'add' screen, so hopefully this will be considered.

**Potential UI/UX Design Sketches**
Right below the **Add** title, there should be a box where the URL is displayed.

**Comment by DesarrolloAntonio** [comment]
thanks, I'll add the url info
