### ISSUE TITLE
[FEATURE] After login error, have button to go straight to the login screen

### ISSUE THREAD

**Issue by Skivling** [DesarrolloAntonio/Shiori-Android-Client#35]
**Is your feature request related to a problem? Please describe.**
A problem relating to the share to PageKeeper functionality. If the session has been reset and the login has error, one presses 'save' then gets a pop-up error. Pressing accept from that screen quits the dialog and then one has to manually open the app again.

**Describe the solution you'd like**
On that pop-up error, instead of just having 'accept', there should also be a button 'go to login' which opens the login screen.

**Describe alternatives you've considered**
It's an inconvenience, but currently I just manually open the app.

**Additional context**
n/a

**Potential UI/UX Design Sketches**
```
| ----------------------------------------- |
|        session expired error              |
|                                           |
|  Go to login                    Accept    |
| ----------------------------------------- |
```
Those bottom bits being buttons, and of course there is still the detailed info in the middle.

**Comment by Skivling** [comment]
It still shows the old one when the error occur after sharing the link to the app. I can screen record the process if you'd like.

**Comment by DesarrolloAntonio** [comment]
> I can screen record the process if you'd like.

Please, thank you

**Comment by Skivling** [comment]
I have to edit out a bunch of personal info that pops up in the share menu, will send video through in the next hour

**Comment by Skivling** [comment]
I can't get any video editors to work, so here are some screenshots.

I click on a link and share:
![pagekeeeper1](https://github.com/DesarrolloAntonio/Shiori-Android-Client/assets/145093975/b40a13be-e26d-4894-a72a-04d78314f263)
Then click on PageKeeper.
It opens up the Add page, and I add a tag and press save and the old error message appears:
![pagekeeper2](https://github.com/DesarrolloAntonio/Shiori-Android-Client/assets/145093975/259f0d11-62c1-45e1-a8e1-9e2fe9bc9d69)


I am running latest version 1.19 and it is the older style error.
I also get that when I go to the main app. I haven't been able to get that newer version yet.

**Comment by DesarrolloAntonio** [comment]
Now I understand, it's when there is a session but it has expired. The screen I have put up appears when there is no session. I'll fix it, thanks.
