### ISSUE TITLE
No bookmarks listed past the first page of Shiori

### ISSUE THREAD

**Issue by erat-verbum** [DesarrolloAntonio/Shiori-Android-Client#36]
**Bug Description**
If I scroll to the bottom of the listed bookmarks on the main page of the app, it does not show any bookmarks beyond the ones listed on the first page in Shiori.

**Steps to Reproduce**
1. Go to the main page of the app
2. Scroll to the bottom and notice the last bookmark
3. Compare to the last bookmark of page 1 in Shiori

**Expected Behavior**
All bookmarks from Shiori should appear.

**Device Information**
- Brand and Model: Pixel 7
- Android Version: Android 14
- App Version: 1.19.1

**Comment by DesarrolloAntonio** [comment]
Can you confirm that bug for me? I've tested on several devices and have not been able to reproduce the problem. Is it possible that the device was using the cache?
Thank you

**Comment by erat-verbum** [comment]
Hi, yes, this continues to be an issue. I uninstalled the app and thrn installed the latest version from IzzyOnDroid (1.21.1), and the problem continued.

Here is the bottom of list on the app:
![Screenshot_20240424-114201](https://github.com/DesarrolloAntonio/Shiori-Android-Client/assets/32501152/d1d40cc5-55f9-4717-934c-92c63ae7602b)

And here is the bottom of the first page on the Shiori web front-end:

![IMG_20240424_114435](https://github.com/DesarrolloAntonio/Shiori-Android-Client/assets/32501152/ec30bb3d-6f56-48d5-801b-026e9338302d)

**Comment by erat-verbum** [comment]
I am running Shiori inside of docker using the following docker-compose:

![IMG_20240424_115033](https://github.com/DesarrolloAntonio/Shiori-Android-Client/assets/32501152/82ef5504-0ef2-417b-bed9-bbc84893e4e9)

**Comment by erat-verbum** [comment]
I use the latest docker image, listed here as being v1.6.2:

https://github.com/go-shiori/shiori/pkgs/container/shiori

I have 30 bookmarks listed on the first page.

**Comment by DesarrolloAntonio** [comment]
Thank you, I will fix the bug as soon as possible

**Comment by erat-verbum** [comment]
Thank you!
