### ISSUE TITLE
[BUG] Error Opening URL into other apps (not browser)

### ISSUE THREAD

**Issue by chri55** [DesarrolloAntonio/Shiori-Android-Client#37]
**Bug Description**
Hi, I'm having an issue and Android where certain links that have a scheme to open in a specific app (GitHub link into the GitHub app for example) will just show "Error Opening URL". This also notably happens in the Settings of the app under "Server Settings Guide" (which I believe is a link to GitHub)

**Steps to Reproduce**
1. Add a GitHub link to PageKeeper
2. Ensure GitHub app can open supported links on Android through the settings
4. Click on the link through pagekeeper
5. See error "Error opening URL"

**Expected Behavior**
The link opens the related app instead of showing an error. Or at least opens in browser.

**Screenshots**
![photo_2024-04-20 09 57 40](https://github.com/DesarrolloAntonio/Shiori-Android-Client/assets/19533506/ab04964f-005a-49d7-9383-8086d5327238)
![photo_2024-04-20 09 57 45](https://github.com/DesarrolloAntonio/Shiori-Android-Client/assets/19533506/da081220-c9d2-4d68-aa28-c3cdc0aa1476)

**Device Information**
- Brand and Model: Google Pixel 6a
- Android Version: 14
- App Version: 1.2.0

**Additional Context**
App is great! Thanks for the work on it.

**Comment by DesarrolloAntonio** [comment]
Fixed in version 1.21.1, tested on links from GitHub, YouTube, TikTok, F-droid... it opens the corresponding app.
Thanks for the feedback.
