### ISSUE TITLE
acsses to the epub

### ISSUE THREAD

**Issue by Monirzadeh** [DesarrolloAntonio/Shiori-Android-Client#4]
user can't download epub version from application

**Comment by DesarrolloAntonio** [comment]
> user can't download epub version from application

![image](https://github.com/DesarrolloAntonio/Shiori-Android-Client/assets/7002198/b88bddee-54f1-4d48-a222-c2ea77851252)
Epub button visible in bookmarks with epub generated

**Comment by DesarrolloAntonio** [comment]
> thanks. i test that and i think i found two problem
> 
> 1. when you try to download it download ebook.epub it better if user download bookmarktitle.epub
>    we do in shiori with this line
> 
> ```
> https://github.com/go-shiori/shiori/blob/84e5b09c4c9944fc881ad6e1c6a5224b6fa07e42/internal/view/content.html#L34
> ```
> 
> so user download folder not be full of `ebook.epub` `ebook(1).epub` `ebook(2).epub`
> 
> 2. pagekeeper just show ebook icon if ebook exist. so user can't request generate ebook for bookmarks that don't have ebook.

1 - I can't do it without first creating a download manager. Currently, what I do is send the API link for the system to handle, a link like the following (http://192.168.1.27:8580/bookmark/10/ebook). With this link, I can't determine the name.
2 - I will add a cloud button as on the website with the options "Keep the old title and excerpt," "Update archive as well," and "Update Ebook as well."

**Comment by DesarrolloAntonio** [comment]
Cloud button added for sync caché in release v1.06

**Comment by DesarrolloAntonio** [comment]
> Hi. i test that and some minor problem happen. as i see currently if you add link from pagekeepr in phone it generate Archive too(not bad but better when readable version added to pagekeeper add an option for that in settings). if you add page from server (without archive check) page keeper open original link (this fine) if you request update archive from pagekeeper or server for bookmark (that don't have archive yet) generate correctly but tap on bookmark send user to original link instead of new archive version.
> 
> 1. add a bookmark in web client uncheck Archive.
> 2. page keeper show that. tap on that redirect user to online version
> 3. request update cache in pagekeeper for that bookmark
> 4. tap on that bookmark pagekeeper still redirect user to online version instead of archive version

I'm going to add two checks when adding a bookmark to create the archive and the epub. As for opening the archive version, the problem I have is that I can't access the link if it's not public, I can't send a cookie from the app to Chrome, Firefox, Edge...

**Comment by DesarrolloAntonio** [comment]
Yes, I can use an internal WebView inside the app

**Comment by DesarrolloAntonio** [comment]
> > Yes, I can use an internal WebView inside the app
> 
> I personally preference readable version in app but when we impeliment Obelisk maybe we can return archive file with api too. Do you think it can help for what you have in mind for app?

If the content of the archive file is HTML, I can download it and load in a Webview.

**Comment by DesarrolloAntonio** [comment]
> > Hi. i test that and some minor problem happen. as i see currently if you add link from pagekeepr in phone it generate Archive too(not bad but better when readable version added to pagekeeper add an option for that in settings). if you add page from server (without archive check) page keeper open original link (this fine) if you request update archive from pagekeeper or server for bookmark (that don't have archive yet) generate correctly but tap on bookmark send user to original link instead of new archive version.
> > 
> > 1. add a bookmark in web client uncheck Archive.
> > 2. page keeper show that. tap on that redirect user to online version
> > 3. request update cache in pagekeeper for that bookmark
> > 4. tap on that bookmark pagekeeper still redirect user to online version instead of archive version
> 
> I'm going to add two checks when adding a bookmark to create the archive and the epub. As for opening the archive version, the problem I have is that I can't access the link if it's not public, I can't send a cookie from the app to Chrome, Firefox, Edge...

- Add the options 'make archive public' and 'Create archive' when adding a bookmark in versión 1.07

**Comment by DesarrolloAntonio** [comment]
> Hi. thanks to add option. i test that today and it work fine. maybe some small improvement can make it better too.
> 
> 1. check box `Make archive publicly available` maybe a little misleading something like `Make bookmark publicly available ` could be more clear. that you know shiori make bookmark available that mean `archive`, `readable version` and `ebook` will be publicly available not jusr archive.
> 2. i try to make that two option disable by default but i can't and each time i should tap on them. is it possible to add default settings for them to the settings menu so user can define default once there if user want change specific bookmark settings than can change them?(less tap each time)
> 3. we can add automatically create ebook to the settings menu too? or add that to add bookmark page make things clutter? what do you think?
> 
> one more extra that i like know your view point I like current adding menu. simple and pleasant specialty `save Bookmark` has prefect place for thumb . is it possible keep things simple like current setup but more reachable to the thumb? it make things clutter or complicated if just move things to the bottom of screen (without force user to tap more that need) but you have more experience than me in design android app. i personally prefer current setup instead of make things complicated (if move things to the bottom of screen make things clutter or complicated or increase user tap)
> 
> dose it need a discussion in discussion section (repository currently don't have discussion section ) or a separate issue for better conclusion?

- Ok, I'll change the title of the checkbox to "Make bookmark publicly available."
- It's a good idea to add the "Create EPUB" option on the add bookmark screen, and I'll create options in the settings to set default values.
- I think the only thing I would move to the bottom are the checkboxes.
- I have opened the discussion section on GitHub.
- Perhaps I could also add another option in the settings to add bookmarks automatically without confirmation.

**Comment by DesarrolloAntonio** [comment]
> > > > 3. we can add automatically create ebook to the settings menu too? or add that to add bookmark page make things clutter? what do you think?
> > 
> > 
> > I'm trying to create the ebook by adding a bookmark with createEbook=true but it doesn't work. It does work when editing.
> 
> In which version? In shiori v1.6 it change to `create_ebook` and `create_archive` can you reference where you send request for create bookmark in code?

Should I always use v1.6? I am using v1.5.5 because it appears as Latest on GitHub.

**Comment by DesarrolloAntonio** [comment]
> No. i don't know this problem happen in which version and i remember that we change that in 1.6. i think shiori 1.6 release soon. can you please link line that send that request in pagekeeper for add bookmark?

{"author":"","createArchive":true,"createEbook":true,"excerpt":"","hasArchive":false,"hasContent":false,"hasEbook":false,"id":-1,"imageURL":"","modified":"","public":1,"tags":[],"title":"","url":"https://www.macworld.com/article/2228152/how-to-view-body-temperature-apple-watch.html"}

**Comment by DesarrolloAntonio** [comment]
> > No. i don't know this problem happen in which version and i remember that we change that in 1.6. i think shiori 1.6 release soon. can you please link line that send that request in pagekeeper for add bookmark?
> 
> {"author":"","createArchive":true,"createEbook":true,"excerpt":"","hasArchive":false,"hasContent":false,"hasEbook":false,"id":-1,"imageURL":"","modified":"","public":1,"tags":[],"title":"","url":"[https://www.macworld.com/article/2228152/how-to-view-body-temperature-apple-watch.html"}](https://www.macworld.com/article/2228152/how-to-view-body-temperature-apple-watch.html%22%7D)

<img src="https://github.com/DesarrolloAntonio/Shiori-Android-Client/assets/7002198/a12479c2-4df0-424e-b6e4-a3dbe0db93d3" width="300">

**Comment by DesarrolloAntonio** [comment]
I've added a new section "Defaults" in settings, version 1.08

**Comment by DesarrolloAntonio** [comment]
> Sorry if this is a silly question, but where is the epub downloaded to?
> 
> I installed the app on my ereader, and it works very well opening the link in the browser, but my ultimate goal is to open the epub in my boox's reader application. However, when I click on the `epub` option, after I'm told it is downloaded, I can't find it anywhere, and I can only share it (and the reader application is not among the possible sharing destinations).
> 
> Could we have a setting `Download folder` and store them there?

Currently, epubs are saved internally within the PageKeeper app's own storage. This approach is chosen to avoid requesting additional permissions from users, such as those needed to access external storage. By keeping everything within the app, we help ensure user data privacy and security.

**Comment by mredaelli** [comment]
> Currently, epubs are saved internally within the PageKeeper app's own storage. This approach is chosen to avoid requesting additional permissions from users, such as those needed to access external storage. By keeping everything within the app, we help ensure user data privacy and security.

I don't think an optional permission to have write access to one specific folder would be too bad under those (sensible) consideration.

Still, I can work around it with an app that allows to share saving to a file, so even though it seems a natural feature to me, I won't press further if you disagree :)

**Comment by DesarrolloAntonio** [comment]
In this issue https://github.com/DesarrolloAntonio/Shiori-Android-Client/issues/8, you can see why I remove the option to save the epub outside the app
