### ISSUE TITLE
[BUG] Not all tags automatically load from web instance of Shiori

### ISSUE THREAD

**Issue by erat-verbum** [DesarrolloAntonio/Shiori-Android-Client#40]
**Bug Description**
If I open the android app and click on the filter icon at the top right, not all the tags show up in the slide-up card. 

However, if I scroll through all the bookmarks before selecting the filter, then all the tags show up.

**Steps to Reproduce**
1. Close the app
2. Open the app and immediately tap the filter button in the top right-hand corner.
3. Observe that not all the tags show up.
4. Now close the filter and scroll to the bottom of all the bookmarks
5. Open up the filter again and you will see all of the tags appear

**Expected Behavior**
All the tags should appear when tapping the filter button, without needing to scroll through all the bookmarks.

**Screenshots**
![Screenshot_20240506-133052](https://github.com/DesarrolloAntonio/Shiori-Android-Client/assets/32501152/484f347f-81d0-4e37-bd17-ff205ec57c0f)

**Device Information**
- Brand and Model: Pixel 7
- Android Version: Android 14
- App Version: 1.30

**Additional Context**

**Comment by in-principio** [comment]
That's a good point.

I think, from a user's perspective, if they have reached 6000 bookmarks, then tags would be pretty much the only way of navigating all of those bookmarks.

So, minimally, I think all the tags should be available offline. And then, when a tag is selected, the associated articles can be downloaded.

**Comment by erat-verbum** [comment]
I can confirm that this is now working for me. Thank you!
