### ISSUE TITLE
[BUG] App crashes when article is opened

### ISSUE THREAD

**Issue by Tauometre** [DesarrolloAntonio/Shiori-Android-Client#48]
**Bug Description**
--App crashes when article is opened

**Steps to Reproduce**
1. Go to 'Site where all articles are'
2. Click on 'any article' 
4. See error 'App Crash to Homescreen'

**Expected Behavior**
-Open the article for viewing

**Screenshots**

**Device Information**
- Brand and Model: [Samsung Galaxy S23 Ultra]
- Android Version: [Android 14 OneUi 6.1]
- App Version: [1.35]

**Additional Context**

**Comment by tim-coder** [comment]
I'm getting the same error.

**Comment by fairplay** [comment]
Seems resolved in 1.5.0 for me, thanks.
