### ISSUE TITLE
Release 1.50 lacks its APK

### ISSUE THREAD

**Issue by IzzySoft** [DesarrolloAntonio/Shiori-Android-Client#51]
Could you please attach the APK to the release, so updater (and rebuilder) at IzzyOnDroid as well as F-Droid can fetch it? Thanks in advance!

**Comment by IzzySoft** [comment]
@DesarrolloAntonio just a heads-up-ping in case you missed (or did not receive) the notification for this issue. Both, IzzyOnDroid as well as F-Droid are stuck with their updates without you attaching the APK (both are verifying whether your APK is reproducible, and then provide your APK (not their self-built one) via their catalogs. So we both just receive errors, and cannot provide the update as we simply have none.

**Comment by IzzySoft** [comment]
Oof… That APK was not built from the commit the tag points to, was it? Tag points to 8559a4e98a1b2df26feb7c47c0fc72669dcc35a4 – APK say it comes from 905450d09ad876a140e6ca0d3c6d715ace8b9a1a, so RB would fail.

```
Checking 'https://api.github.com/repos/DesarrolloAntonio/Shiori-Android-Client/releases/latest'...
Found tag 'v1.50' with APK URL 'https://github.com/DesarrolloAntonio/Shiori-Android-Client/releases/download/v1.50/Shiori.v1.50.apk'.
Updated 'com.desarrollodroide.pagekeeper' to 'v1.50'.
Recipe git reset: '905450d09ad876a140e6ca0d3c6d715ace8b9a1a', tag: '8559a4e98a1b2df26feb7c47c0fc72669dcc35a4'.
Updated hashes for 'com.desarrollodroide.pagekeeper:v1.50'.
```

Though the additional commits only changed your workflow files (and not the app code), the commit hash is embedded in the APK (luckily, as that often helps identify mismatches) – so for future releases, please ensure that tagged-commit and build-commit are identical (i.e. that you build from a clean tree at the tagged commit). I had to adjust the recipe manually here (F-Droid will need the same then).

Next, I see you now introduced build flavors (`production` and `staging`). I assume you used `assembleProductionRelease` for the APK attached to your release? OK, fits and is RB.

So @licaon-kter (I saw you're already watching this): `gradle: yes` needs to become `gradle: production` for you, and build from 905450d09ad876a140e6ca0d3c6d715ace8b9a1a instead of the tagged commit (I just did a `git reset --soft` here, but the outcome should be the same as no source files are effected by the commits in between).

**Comment by licaon-kter** [comment]
yup @linsui alfready updated the gradle flavor
